#!/usr/bin/env bash
# make-env.sh — generate server/.env on the box, interactively.
#
# Auto-generates the two random secrets (JWT_SECRET, ASSISTANT_API_TOKEN) and
# prompts for the two values only you have (MONGO_URI, ANTHROPIC_API_KEY).
# No secrets are baked into this file, so it is safe to keep in the public repo.
#
# Run on the box:  bash make-env.sh
set -euo pipefail

ENV_PATH="${1:-/var/www/moduli/server/.env}"
DEPLOY_USER="deploy"
FORCE="${FORCE:-0}"

# ── Guard against clobbering an existing .env ────────────────────────────────
if [ -f "$ENV_PATH" ] && [ "$FORCE" != "1" ]; then
  echo "!! $ENV_PATH already exists. Re-run with FORCE=1 to overwrite:"
  echo "   FORCE=1 bash make-env.sh $ENV_PATH"
  exit 1
fi

# Read prompts from the terminal even if the script was piped in.
if [ -r /dev/tty ]; then exec 3</dev/tty; else exec 3<&0; fi

echo "==> Generating server/.env at: $ENV_PATH"
echo ""

# ── 1. MONGO_URI (required) ──────────────────────────────────────────────────
echo "Paste your full Atlas connection string (MONGO_URI)."
echo "  e.g. mongodb+srv://USER:PASS@host.mongodb.net/moduli?retryWrites=true&w=majority"
printf "MONGO_URI: "
read -r MONGO_URI <&3
if [[ "$MONGO_URI" != mongodb*://* ]]; then
  echo "!! That doesn't look like a MongoDB URI (must start with mongodb:// or mongodb+srv://). Aborting." >&2
  exit 1
fi
# Nudge if the /moduli database name is missing from the path.
if ! printf '%s' "$MONGO_URI" | grep -qE '\.net/[A-Za-z0-9_-]+(\?|$)'; then
  echo "   (heads up: I don't see a '/moduli' database name in the path — double-check it's there.)"
fi

# ── 2. ANTHROPIC_API_KEY (optional) ──────────────────────────────────────────
echo ""
echo "Anthropic API key for the assistant (optional — press Enter to skip)."
echo "  Find it at console.anthropic.com -> Settings -> API Keys. Starts with sk-ant-..."
printf "ANTHROPIC_API_KEY: "
read -r ANTHROPIC_API_KEY <&3

# Pick the assistant backend: anthropic if a key was given, else deterministic
# (Ollama is off on this box, so we never want it probing localhost:11434).
if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
  ASSISTANT_BACKEND="anthropic"
else
  ASSISTANT_BACKEND="deterministic"
fi

# ── 3. Auto-generated secrets ────────────────────────────────────────────────
JWT_SECRET="$(openssl rand -hex 32)"
ASSISTANT_API_TOKEN="moduli_$(openssl rand -hex 24)"

# ── 4. Write the file (tight perms from the start) ───────────────────────────
mkdir -p "$(dirname "$ENV_PATH")"
( umask 077; cat > "$ENV_PATH" <<EOF
# Moduli production env — generated by make-env.sh. DO NOT COMMIT.
MONGO_URI=$MONGO_URI
PORT=5000

# Strong random secret (openssl rand -hex 32)
JWT_SECRET=$JWT_SECRET

# Assistant: anthropic | ollama | deterministic
ASSISTANT_BACKEND=$ASSISTANT_BACKEND
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY

# Random token guarding assistant API routes (openssl rand -hex 24)
ASSISTANT_API_TOKEN=$ASSISTANT_API_TOKEN

# Ignored while Ollama is off, kept for when ENABLE_OLLAMA flips on.
OLLAMA_MODEL=llama3.2:3b
EOF
)
chmod 600 "$ENV_PATH"

# If we're root and the deploy user exists, hand the file to them.
if [ "$(id -u)" = "0" ] && id "$DEPLOY_USER" >/dev/null 2>&1; then
  chown "$DEPLOY_USER:$DEPLOY_USER" "$ENV_PATH"
fi

echo ""
echo "✅ Wrote $ENV_PATH"
echo "   MONGO_URI            = <set>"
echo "   JWT_SECRET           = <generated, 64 hex chars>"
echo "   ASSISTANT_API_TOKEN  = <generated>"
echo "   ASSISTANT_BACKEND    = $ASSISTANT_BACKEND"
echo "   ANTHROPIC_API_KEY    = $([ -n "${ANTHROPIC_API_KEY:-}" ] && echo '<set>' || echo '<blank — assistant runs in deterministic mode>')"
echo ""
echo "   Next:  bash provision.sh   (re-run to finish nginx + pm2)"
