// models/Field.js
import mongoose from "mongoose";

const FieldSchema = new mongoose.Schema(
  {
    // Unique identifier (UUID generated by client)
    id: { type: String, required: true, index: true, unique: true },

    userId: { type: String, required: true, index: true },

    // Grid this field belongs to (fields are grid-level entities)
    gridId: { type: String, required: true, index: true },

    // Field name
    name: { type: String, required: true, trim: true },

    // Field data type
    type: {
      type: String,
      required: true,
      enum: ["number", "text", "boolean", "select", "date", "rating", "duration", "occurrence", "markdown"],
      default: "text"
    },

    // Optional unit (for number fields)
    unit: { type: String },

    // Whether the field accepts user input (shows FieldInput widget)
    inputEnabled: { type: Boolean, default: true },

    // Whether the field shows a computed display value (written by operations)
    // displayEnabled fields get their value from operation ACTION(SEND_TO_DISPLAY) blocks
    // Values are stored in client React state (computedValues), NOT in the DB
    displayEnabled: { type: Boolean, default: false },

    // Display config: visual settings for display fields. The progress bar +
    // value/target string in Field.jsx fall back to these when an op doesn't
    // publish a target via UPDATE_DISPLAY_VALUE.
    displayConfig: {
      // Show up/down arrows when value changes (green = up, red = down)
      showArrows: { type: Boolean, default: false },
      // Hardcoded arrow color instead of auto (optional)
      arrowColor: { type: String, enum: ["green", "red", "auto", null], default: null },
      // Numeric goal value rendered as the progress bar's max
      targetValue: { type: Number, default: null },
      // Period the target applies to — used to scale e.g. weekly→daily views
      targetPeriod: { type: String, enum: ["daily", "weekly", "monthly", "yearly", null], default: "daily" },
    },

    // Category folder — references a Folder with folderType "category"
    folderId: { type: String, default: null },

    // Optional metadata (prefix, postfix, increment, select options, placeholder, etc.)
    meta: { type: mongoose.Schema.Types.Mixed, default: {} },

    // Sibling links (for linked fields: Q&A pairs, etc.)
    siblingLinks: { type: [String], default: [] },
  },
  {
    timestamps: true,
    minimize: false,
  }
);

// Indexes for queries
FieldSchema.index({ userId: 1, gridId: 1 });
FieldSchema.index({ gridId: 1, name: 1 });

// Hide Mongo internals in API responses
FieldSchema.set("toJSON", {
  virtuals: true,
  versionKey: false,
  transform: (_, ret) => {
    ret._id = ret._id?.toString?.() ?? ret._id;
    return ret;
  },
});

export default mongoose.model("Field", FieldSchema);
