// models/Folder.js
// ============================================================
// FOLDER: Tree node for organizing artifacts and docs
// Part of the ArtifactManager system
// ============================================================

import mongoose from "mongoose";

const FolderSchema = new mongoose.Schema(
  {
    // Unique identifier (UUID generated by client)
    id: { type: String, required: true, index: true, unique: true },

    userId: { type: String, required: true, index: true },

    // gridId is optional — folders are user-scoped (accessible from any grid)
    gridId: { type: String, index: true },

    // Folder hierarchy
    parentId: { type: String, default: null, index: true }, // null = root level

    // Display info
    name: { type: String, default: "New Folder" },
    icon: { type: String, default: "folder" }, // icon name or emoji
    color: { type: String, default: null }, // optional color override

    // Order within parent folder
    sortOrder: { type: Number, default: 0 },

    // Expansion state (for tree UI)
    isExpanded: { type: Boolean, default: true },

    // Special folder types
    folderType: {
      type: String,
      enum: ["normal", "trash", "templates", "day-pages", "category"],
      default: "normal",
    },

    // Optional metadata
    meta: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  {
    timestamps: true,
    minimize: false,
  }
);

// Compound indexes
FolderSchema.index({ userId: 1, parentId: 1 });
FolderSchema.index({ userId: 1, sortOrder: 1 });

// Hide Mongo internals
FolderSchema.set("toJSON", {
  virtuals: true,
  versionKey: false,
  transform: (_, ret) => {
    ret._id = ret._id?.toString?.() ?? ret._id;
    return ret;
  },
});

export default mongoose.model("Folder", FolderSchema);
