// models/Folder.js
// ============================================================
// FOLDER: Tree node for organizing artifacts and docs
// Part of the ArtifactManager system
// ============================================================

import mongoose from "mongoose";

const FolderSchema = new mongoose.Schema(
  {
    // Unique identifier (UUID generated by client)
    id: { type: String, required: true, index: true, unique: true },

    userId: { type: String, required: true, index: true },

    // gridId is optional — folders are user-scoped (accessible from any grid)
    gridId: { type: String, index: true },

    // Folder hierarchy
    parentId: { type: String, default: null, index: true }, // null = root level

    // Display info
    name: { type: String, default: "New Folder" },
    icon: { type: String, default: "folder" }, // icon name or emoji
    color: { type: String, default: null }, // optional color override

    // Order within parent folder
    sortOrder: { type: Number, default: 0 },

    // Expansion state (for tree UI)
    isExpanded: { type: Boolean, default: true },

    // Special folder types
    folderType: {
      type: String,
      enum: ["normal", "trash", "templates", "day-pages", "category", "global", "grid", "panel"],
      default: "normal",
    },

    // Which AXIS a folderType:"category" folder groups (2026-07-13): "field"
    // (FieldsTab columns) or "op" (OperationsTab columns). Stamped at creation
    // by whichever tab minted it + by the seed. IDENTITY AS DATA — before
    // this, both tabs GUESSED the axis from the folder's current contents, so
    // classification flipped as a side effect of unrelated deletes (an op
    // category whose last op is deleted read as a field category, and every
    // op category rendered as an empty column in FieldsTab). null = legacy
    // folder → tabs fall back to the contents inference.
    categoryKind: { type: String, default: null },

    // Links panel folder to its panel module (only for folderType: "panel")
    panelId: { type: String, default: null, index: true },

    // Optional metadata
    meta: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  {
    timestamps: true,
    minimize: false,
  }
);

// Compound indexes
FolderSchema.index({ userId: 1, parentId: 1 });
FolderSchema.index({ userId: 1, sortOrder: 1 });

// Hide Mongo internals
FolderSchema.set("toJSON", {
  virtuals: true,
  versionKey: false,
  transform: (_, ret) => {
    ret._id = ret._id?.toString?.() ?? ret._id;
    return ret;
  },
});

FolderSchema.index({ userId: 1, gridId: 1 });

export default mongoose.model("Folder", FolderSchema);
