// models/Occurrence.js
import mongoose from "mongoose";

const OccurrenceSchema = new mongoose.Schema(
  {
    // Unique identifier (UUID generated by client)
    id: { type: String, required: true, index: true, unique: true },

    userId: { type: String, required: true, index: true },

    // Reference to the Module record this placement renders.
    moduleId: { type: String, required: true, index: true },

    // Grid this occurrence belongs to
    gridId: { type: String, required: true, index: true },

    // Filter override — controls how this occurrence (panel/container) inherits filter context
    // null = inherit parent's effective filter values (grid → panel → container)
    // {} = clear all filters (show everything regardless of active filter)
    // { [fieldId]: value } = use these specific values instead of parent's
    filterOverride: { type: mongoose.Schema.Types.Mixed, default: null },

    // Hidden flag — set by HIDE_OCCURRENCE operation effect
    hidden: { type: Boolean, default: false },

    // Locked flag — when true, doc editor is read-only
    locked: { type: Boolean, default: false },

    // Timestamp for this occurrence
    timestamp: { type: Date, default: Date.now, index: true },

    // Panel placement (only used when the module is role: "panel")
    placement: {
      row: { type: Number },
      col: { type: Number },
      width: { type: Number },
      height: { type: Number }
    },

    // Optional snapshot of field values (for UI convenience)
    fields: { type: mongoose.Schema.Types.Mixed, default: {} },

    // View reference — viewId → View model record (SEPARATE model, NOT embedded)
    viewId: { type: String, default: null, index: true },

    // TipTap JSON content. Synced bidirectionally with artifacts/ files.
    textmap: { type: mongoose.Schema.Types.Mixed, default: null },

    // Parent occurrence ID (tree structure)
    parentId: { type: String, default: null, index: true },

    // Ordered child occurrence IDs
    occurrences: { type: [String], default: [] },

    // Copylink: linked occurrence ID — when set, field edits propagate to all
    // occurrences sharing the same linkedGroupId
    linkedGroupId: { type: String, default: null, index: true },

    // Sort order within parent (used by ManifestTree anchors, folder items, etc.)
    sortOrder: { type: Number, default: 0 },

    // Per-occurrence drag mode override (overrides module.defaultDragMode when set)
    dragMode: { type: String, enum: ["move", "copy", "copylink"], default: null },

    // Optional metadata
    meta: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  {
    timestamps: true,
    minimize: false,
  }
);

OccurrenceSchema.index({ gridId: 1, timestamp: -1 });
OccurrenceSchema.index({ moduleId: 1, gridId: 1 });

OccurrenceSchema.set("toJSON", {
  versionKey: false,
  transform: (_, ret) => {
    ret._id = ret._id?.toString?.() ?? ret._id;
    return ret;
  },
});

export default mongoose.model("Occurrence", OccurrenceSchema);
