// models/Occurrence.js
import mongoose from "mongoose";

const OccurrenceSchema = new mongoose.Schema(
  {
    // Unique identifier (UUID generated by client)
    id: { type: String, required: true, index: true, unique: true },

    userId: { type: String, required: true, index: true },

    // Reference to the Module record this placement renders.
    moduleId: { type: String, required: true, index: true },

    // Grid this occurrence belongs to
    gridId: { type: String, required: true, index: true },

    // Filter override — controls how this occurrence (panel/container) inherits filter context
    // null = inherit parent's effective filter values (grid → panel → container)
    // {} = clear all filters (show everything regardless of active filter)
    // { [fieldId]: value } = use these specific values instead of parent's
    filterOverride: { type: mongoose.Schema.Types.Mixed, default: null },

    // Per-occurrence nav widget config keyed by filter id (Grid.namedFilters[i].id).
    // Each entry carries { visible, style, options?, step? } to drive type-dispatched
    // nav widgets (arrows / pills / input / custom). Default {} = no nav shown.
    filterNavConfig: { type: mongoose.Schema.Types.Mixed, default: {} },

    // Per-occurrence local filter list edited via FilterEditor (HeaderDropdown cog).
    // Each entry: { id, fieldId, active, showNav, timeUnit, defaultNavValue, condition, allowBlank }.
    // Distinct from filterOverride (a keyed value map) and filterNavConfig (per-filter widget config) —
    // this carries the per-occurrence filter rule rows with optional condition groups.
    filters: { type: [mongoose.Schema.Types.Mixed], default: [] },

    // Per-occurrence field-visibility (which instance fields render inside this
    // occurrence's descendants). Shape: { mode: "show"|"hide", fieldIds: [] } or
    // null. Cascades to descendant instances the same way filters[] does — a
    // child inherits the nearest ancestor's setting unless it sets its own or
    // explicitly turns it off (mode: "off"). Distinct from filterOverride/filters
    // (value filters) — this only governs which field rows are shown, not row
    // visibility. Consumed by ModuleInstance via getEffectiveFieldVisibility.
    fieldVisibility: { type: mongoose.Schema.Types.Mixed, default: null },

    // Feed (2026-07-07): pull-query rendering. When set + enabled, renderers
    // display occurrences matching `conditions` (filter-menu condition rows)
    // ALONGSIDE the occurrence's own children. Pure VIEW — pulled items are
    // never re-parented (ancestry is load-bearing for the filter cascade +
    // tracker HAS_ANCESTOR scopes); feed rows drag in copy mode only.
    // Shape: { enabled, conditions:[{id,fieldId,comparator,value}],
    //          roles:["instance"], scope:<occId>|null, sort:{fieldId,dir}|null,
    //          limit:50, layout:{ [occId]: {x,y} } } — layout is the canvas
    //          view's own positions for pulled cards (canvas-local by design).
    feed: { type: mongoose.Schema.Types.Mixed, default: null },

    // Template merge identity. When set on a template-side occurrence, APPLY_TEMPLATE
    // in mode:"merge" treats any sibling under the apply target with the same
    // identitySignature as "the same node" — skips cloning, recurses into its
    // template children. Empty/null = always create a fresh clone on each apply.
    identitySignature: { type: String, default: null, index: true },

    // Per-placement label override. null = render the module's own label.
    // When set, the renderer shows this instead (ModuleInstance/ModuleContainer
    // prefer occurrence.label over module.label). Written by ops via the
    // UPDATE_ITEM_LABEL effect (path `$occ.label`) — e.g. the date-prefix
    // goal/tracker labels ("Today's Water", "July 18th Water"). The module
    // label stays the stable base; this is the decorated per-occurrence view.
    label: { type: String, default: null },

    // Hidden flag — set by HIDE_OCCURRENCE operation effect
    hidden: { type: Boolean, default: false },

    // Locked flag — when true, doc editor is read-only
    locked: { type: Boolean, default: false },

    // Timestamp for this occurrence
    timestamp: { type: Date, default: Date.now, index: true },

    // Panel placement (only used when the module is role: "panel")
    placement: {
      row: { type: Number },
      col: { type: Number },
      width: { type: Number },
      height: { type: Number }
    },

    // Optional snapshot of field values (for UI convenience)
    fields: { type: mongoose.Schema.Types.Mixed, default: {} },

    // Per-field last-write timestamp map: `{ [fieldId]: epochMs }`. Bumped
    // every time a field is written. Powers #26 medium-tier conflict
    // resolution: two windows writing DIFFERENT fields auto-merge; two
    // writing the SAME field produce a per-field collision the client
    // resolves explicitly. Mixed-type because Mongoose can't index per-
    // key arbitrary fieldIds; the executor reads it as a plain object.
    fieldUpdatedAt: { type: mongoose.Schema.Types.Mixed, default: {} },

    // View reference — viewId → View model record (SEPARATE model, NOT embedded)
    viewId: { type: String, default: null, index: true },

    // TipTap JSON content. Synced bidirectionally with artifacts/ files.
    textmap: { type: mongoose.Schema.Types.Mixed, default: null },

    // Parent occurrence ID (tree structure)
    parentId: { type: String, default: null, index: true },

    // Ordered child occurrence IDs
    occurrences: { type: [String], default: [] },

    // Copylink: linked occurrence ID — when set, field edits propagate to all
    // occurrences sharing the same linkedGroupId
    linkedGroupId: { type: String, default: null, index: true },

    // Sort order within parent (used by ManifestTree anchors, folder items, etc.)
    sortOrder: { type: Number, default: 0 },

    // Per-occurrence drag mode override (overrides module.defaultDragMode when set)
    dragMode: { type: String, enum: ["move", "copy", "copylink"], default: null },

    // Per-occurrence style overlay — overlays module.ownStyle at render time
    // (see helpers/StyleHelpers.resolveContainerStyle/resolveInstanceStyle).
    // Settable via the occurrence settings menu OR by operations writing to
    // path `$occ.ownStyle.<key>` (UPDATE_ITEM_OWN_STYLE effect). Same shape
    // as module.ownStyle: { bg, textColor, border, borderRadius, opacity, ... }.
    ownStyle: { type: mongoose.Schema.Types.Mixed, default: null },

    // Optional metadata
    meta: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  {
    timestamps: true,
    minimize: false,
  }
);

OccurrenceSchema.index({ gridId: 1, timestamp: -1 });
OccurrenceSchema.index({ moduleId: 1, gridId: 1 });
// Compound (userId, gridId) — every full_state load runs
// `Occurrence.find({ userId, gridId })`. Without this index, Mongo picks
// the single-field userId index and filters gridId in-memory; for users
// with multiple grids that means scanning every doc the user owns.
// Diagnostic baseline: Atlas Serverless ran this query in 9.3s for 615
// docs against single-field indexes only.
OccurrenceSchema.index({ userId: 1, gridId: 1 });
// Ingest dedupe. POST /api/v1/ingest resolves "have I already stored this
// external record?" as `{ userId, gridId, meta.source, meta.externalId }` on
// EVERY incoming record, so a backfill runs one lookup per row. Sparse because
// only ingested occurrences carry these keys — hand-made rows must not bloat
// the index. NOT unique: uniqueness is enforced by the deterministic
// occurrence id (see ingestOccId), which fails a concurrent double-write on
// the primary key instead of racing this lookup.
OccurrenceSchema.index(
  { userId: 1, gridId: 1, "meta.source": 1, "meta.externalId": 1 },
  { sparse: true },
);

OccurrenceSchema.set("toJSON", {
  versionKey: false,
  transform: (_, ret) => {
    ret._id = ret._id?.toString?.() ?? ret._id;
    return ret;
  },
});

export default mongoose.model("Occurrence", OccurrenceSchema);
