// models/Occurrence.js
import mongoose from "mongoose";

const OccurrenceSchema = new mongoose.Schema(
  {
    // Unique identifier (UUID generated by client)
    id: { type: String, required: true, index: true, unique: true },

    userId: { type: String, required: true, index: true },

    // What this occurrence represents. Field is now redundant with the
    // referenced module's role; defaults to "module" so writes don't need
    // to specify it. Phase 3 will drop the field entirely.
    targetType: {
      type: String,
      default: "module",
      enum: ["module"],
      index: true
    },
    targetId: { type: String, required: true, index: true },
    // moduleId is the canonical name in the drag/drop pipeline. The DB field
    // is still targetId (no migration yet); the virtual below exposes both
    // names so the drag/drop layer can read/write `moduleId` cleanly while
    // the rest of the codebase keeps using `targetId`.

    // Grid this occurrence belongs to
    gridId: { type: String, required: true, index: true },

    // Filter override — controls how this occurrence (panel/container) inherits filter context
    // null = inherit parent's effective filter values (grid → panel → container)
    // {} = clear all filters (show everything regardless of active filter)
    // { [fieldId]: value } = use these specific values instead of parent's
    filterOverride: { type: mongoose.Schema.Types.Mixed, default: null },

    // Hidden flag — set by HIDE_OCCURRENCE operation effect
    // Checked during container render to skip this occurrence
    hidden: { type: Boolean, default: false },

    // Locked flag — when true, doc editor is read-only
    locked: { type: Boolean, default: false },

    // Timestamp for this occurrence
    timestamp: { type: Date, default: Date.now, index: true },

    // Panel placement (only used when targetType = "panel")
    placement: {
      row: { type: Number },
      col: { type: Number },
      width: { type: Number },
      height: { type: Number }
    },

    // Optional snapshot of field values (for UI convenience)
    // Actual field values can also be computed from transactions in Phase 3
    fields: { type: mongoose.Schema.Types.Mixed, default: {} },

    // View reference — viewId → View model record (SEPARATE model, NOT embedded)
    // View drives rendering: viewType, hasTree, manifestId, activeOccurrenceId, layout
    // Module has NO viewId. View always lives on the occurrence.
    viewId: { type: String, default: null, index: true },

    // TipTap JSON content (replaces docContent). Synced bidirectionally with artifacts/ files.
    // For .md files: textmap ↔ markdown with @:(id) markers on disk.
    textmap: { type: mongoose.Schema.Types.Mixed, default: null },

    // Parent occurrence ID (tree structure — replaces module.occurrences ordering)
    parentId: { type: String, default: null, index: true },

    // Ordered child occurrence IDs (moves FROM module.occurrences to here)
    // For markdown artifacts: order implicit in TipTap doc structure (this array unused)
    // For list/board: this array defines child ordering
    occurrences: { type: [String], default: [] },

    // Copylink: linked occurrence ID — when set, field edits propagate to all
    // occurrences sharing the same linkedGroupId
    linkedGroupId: { type: String, default: null, index: true },

    // Sort order within parent (used by ManifestTree anchors, folder items, etc.)
    sortOrder: { type: Number, default: 0 },

    // Per-occurrence drag mode override (overrides module.defaultDragMode when set)
    dragMode: { type: String, enum: ["move", "copy", "copylink"], default: null },

    // Optional metadata
    meta: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  {
    timestamps: true,
    minimize: false,
  }
);

// Compound indexes for common queries
OccurrenceSchema.index({ gridId: 1, targetType: 1 });
OccurrenceSchema.index({ gridId: 1, timestamp: -1 });
OccurrenceSchema.index({ targetId: 1, gridId: 1 });

// Virtual alias: moduleId ↔ targetId. The drag/drop pipeline reads/writes
// `moduleId`; everywhere else still uses `targetId`. With `toJSON: { virtuals: true }`
// below, Occurrences serialized to clients carry both fields.
OccurrenceSchema.virtual("moduleId")
  .get(function () { return this.targetId; })
  .set(function (v) { this.targetId = v; });

// Defensive pre-validate hook: if a caller constructs `new Occurrence({ moduleId })`
// where the Mongoose constructor route bypasses the virtual setter, copy the
// raw payload value over to targetId before required-field validation runs.
OccurrenceSchema.pre("validate", function (next) {
  if (!this.targetId && this._doc?.moduleId) this.targetId = this._doc.moduleId;
  next();
});

// Hide Mongo internals in API responses
OccurrenceSchema.set("toJSON", {
  virtuals: true,
  versionKey: false,
  transform: (_, ret) => {
    ret._id = ret._id?.toString?.() ?? ret._id;
    return ret;
  },
});
OccurrenceSchema.set("toObject", { virtuals: true });

export default mongoose.model("Occurrence", OccurrenceSchema);
